### PR TITLE
Add SNS and SQS commands with unit tests

### PR DESCRIPTION
**Pull request by DominicBreuker**
#### Card

Two commands `sns` and `sqs` which list queues and topics with access policies granting public access. 
Useful to me for quick screening when there are too many to look at manually. Queues and topics can easily go into the thousands.

Useful for cloudfox?

#### Details

The commands basically just list the resources, get their policies and analyse them. Then they can flag queues and topics in 3 different ways:
- `public` if the principal is `*` and there are no conditions
- `public-wc` (public with conditions). if principal is `*` and there are conditions which do not scope access down to specific accounts  
- not flagged if principal is not `*` or if principal is `*` and at least one condition scopes access down to specific accounts (e.g., SNS topics can set a `aws:SourceAccount` condition, there are other cases)

I've added unit tests this time. Unfortunately I wrote them before noticing the mock file system you introduced. If you generally like and want to merge the command I'm happy to switch to the mock file system. 

The (hopefully) reusable logic lives in a package within the `/pkg` folder. Note that this is a common Go way of encouraging reuse (https://github.com/golang-standards/project-layout). If you avoid this on purpose better rename.

### CODE REVIEW

**Comment by sethsec-bf** [comment]
This is amazing stuff @DominicBreuker, thank you! We'll start playing around and looking at this soon. Enjoy your weekend!

**Comment by sethsec-bf** [comment]
@DominicBreuker - Sorry it took us so long to get to this one. Before touching any of your code, the first thing i did was merge in the new format and improvements we've made to the main branch in v1.9.0.  We really appreciate your reference to the unofficial golang-standards doc, and we used that doc to create a new /internal folder. I've moved your stuff from /pkg to that folder for now to keep it consistent with our new changes. 

So now to your PR. This is of course very helpful and a great addition to cloudfox, but i have a few thoughts: 

* What about merging your two columns into one and making it a little more descriptive. Maybe the header is something like "accessibility" or "resource policy". And the options can be "Public", "Public with conditions", and maybe we can build a short list of other short descriptions.  

* I'm also wondering if we might want to be more explicit on the actions that are allowed by the resource policy. I think it would really cool to have cloudfox tell us if we're talking about a queue/topic that can be read/subscribed to anonymously, or a queue/topic where anyone can send messages, or all of other combos.  

I've started trying to implement both of these, but i'd still like to hear your feedback on them. And on the second one, i might need your help on the policy stuff. I'll let you know. 

Thanks again for this awesome work!

**Comment by DominicBreuker** [comment]
hmm:
- more descriptive column: yes makes perfect sense. my main use case was grepping through the output, which would still be possible but the output is more compact this way. as for more descriptions, maybe we could be more explicit about what conditions apply, but I'd have to research a bit (there are many: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#AvailableKeys + service-specific ones).
- allowed actions: like it a lot. maybe it could be a column `Access Level` code like `r|w|p|t` for `read`, `write`, `permissions` and `tagging`, which would correspond to the access levels from the AWS docs (e.g., https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsqs.html).

**Comment by sethsec-bf** [comment]
@DominicBreuker - Take a look at the stuff I added. It took me a while but I eventually realized how your resource policy logic can be expanded to all services with resource policies. that you so much for this amazing foundation! i took a shot at copying your logic into the buckets command.  and i also took many many shots at trying to represent data in the resource policies in a way that is helpful. 

I still need to add loot writers to sns/sqs to give users the rough idea of the commands they would need to publish to a queue/topic, so that will be the next commit. 

but i wanted to get this code pushed so that you could try it out and let me know if you think it makes sense.  

lastly, i have not touched your tests so i assume those will fail for now.

**Comment by sethsec-bf** [comment]
This PR is ready to merge into main. Thanks again for all of the great work @DominicBreuker.

**Pull request merged**
