### PR TITLE
Identify Potentially Exposed Network Ports

### PR DESCRIPTION
**Pull request by wdahlenburg**
#### About

This PR is currently a draft to cover https://github.com/BishopFox/cloudfox/issues/17. It implements a linked list to process the network ACLs and security groups for a given resource to determine potentially exposed network services. It adds support for the following services:

- EC2
- ECS
- EFS
- ElastiCache
- ELBv2
- Lightsail
- RDS

Loot is created, which splits out IPv4 and IPv6 hosts for network scanning. The services are prefixed with basic nmap syntax, however the CSV or table formats exist as well for users wishing to format their own scans.

#### Details

A linked list is used to maintain the network ACLs for a given VPC. Only ingress rules are kept in this module.

As an MVP, the evaluation of the network ACLs and the security groups doesn't take the source IP into consideration. It simply evaluates if any ports could be exposed on the host. This was done for several reasons:

1. A user may or may not have the ability to change their source IP to interact with AWS services
2. I'm unaware of a consistent methodology to retrieve the source IP that AWS uses to perform the evaluation. NAT and similar layering can make it difficult for every client to evaluate this.
3. There is an increase in code complexity to recursively lookup security groups and manage all of the CIDRs

The loot output tries to encourage users to enumerate from different IPs. Conceptually, I may want to rescan a host from a different VPC or subnet if the a service may be exposed, but the network access isn't initially allowed.

**EC2**
The EC2 logic loops over each security group rule and determines if the network ACL entry permits the allowed ingress traffic. A map, `naclToSG`, was used to map supported protocols between network ACLs and security groups. Essentially "all", "tcp", and "udp" are supported.

The logic is applied to each instance, where the tcp and udp ports are then listed. The output can be broad or strict depending on how loose the ingress rules are.

**ECS**
This task loops over all of the ECS clusters. For each cluster, the associated services are looked up. The tasks associated with each service can finally be looked up. The network interface can be found on the describe-tasks call, which can be used to look up the IPs associated with the task.

Tasks may open up a port on the container, but this will still be dependent on the security groups and network ACLs applied to the service/task.

**EFS**
EFS runs on NFSv4, which AWS describes as only running on TCP port 2049. This task loops over the available file systems and looks up the mount targets for each of them. Each mount target lists a network interface, which can be looked up to obtain the security groups applied to it and the IPs. The standard resolution is performed to see what TCP ports can be accessed. A quick check is done to determine if TCP port 2049 is in the returned list of ports.

**ElastiCache**
ElastiCache can have memcached or Redis services on a user-specified port. The memcached servers will display the dns name when running through describe-cache-clusters. The Redis services don't store their details in the same fields, so the replication groups need to be looked up. The associated endpoints can be added.

A quick check is done to see if the user-specified port is allowed by the security groups and network ACLs.

**ELBv2**
ALBs and NLBs can be mapped to TCP/UDP ports. Gateway load balancers run on layer 3, so they are filtered out.

Each load balancer type allows for the listeners to be queried, which define the protocol and port they listen on. ALBs define security groups, however NLBs do not. To circumvent this, a catch-all security group is added to the list of security groups for a NLB to allow all TCP and UDP traffic when evaluating potentially open ports. NLBs are entirely dependent on the network ACLs for the subnet(s) that they exist in.

**Lightsail**
Lightsail ports are the simplest to refer to. Essentially a protocol and fromPort to toPort range are provided. Lightsail doesn't use VPCs or security groups, so the defined networking configuration is added directly to the network services.

**RDS**
The RDS logic applies the same methodology, but checks the single RDS port against the open TCP ports. Each instance is looped over. If an instance belongs to a cluster, the cluster Endpoint and ReadEndpoint are added to the output after the first time a cluster instance is seen.

TODO:

- FSx

Note: BeanStalk was removed, due to the fact that it just creates other network services, such as EC2s. This would lead to duplicate results.

---

Some refactoring could definitely help. What do you think about the current implementation?

### CODE REVIEW

**Comment by sethsec-bf** [comment]
@wdahlenburg This PR is looking really good.

> Loot is created, which splits out IPv4 and IPv6 hosts for network scanning. The services are prefixed with basic nmap syntax, however the CSV or table formats exist as well for users wishing to format their own scans.

I like that you split out IPv4 and IPv6. What are your thoughts about separating your loot files to be a privateIP and publicIP loot?  So instead of `loot/network-ports-ipv4.txt` you would have `loot/network-ports-private-ipv4.txt` and `loot/network-ports-public-ipv4.txt` ? 

> As an MVP, the evaluation of the network ACLs and the security groups doesn't take the source IP into consideration. It simply evaluates if any ports could be exposed on the host. This was done for several reasons:

i totally get that and it makes sense. Good idea to keep it simple.

> * A user may or may not have the ability to change their source IP to interact with AWS services
> * I'm unaware of a consistent methodology to retrieve the source IP that AWS uses to perform the evaluation. NAT and > similar layering can make it difficult for every client to evaluate this.
> * There is an increase in code complexity to recursively lookup security groups and manage all of the CIDRs

When you do get to it, I think you don't have to have your cloudfox command do this, rather, i think you can ask the user to input the source ip as an optional parameter which will kick off that future functionality that takes source ip into account. i agree that sometimes the user won't know all of the NATing that takes place, but i think we can push that part to the user and just say... given the IP you give us, we will try to give you the output based on that src ip. 

> The logic is applied to each instance, where the tcp and udp ports are then listed. The output can be broad or strict depending on how loose the ingress rules are.

I tried it out and the logic all looks great from my initial tests.  Gave me expected results for my test environments. 

Some other suggestions: 

* You could potentially allow the user to specify their own nmap syntax at the cloudfox command line. On one hand this is probably not that hard to add, but on the other hand, i'm not sure how many would use this. just a thought. 
* I wonder if you should add the `-oA [prefix]` where prefix is based on the host your are scanning. I do something similar in the buckets loot file.  
* If you do have your nmap commands include the `-oA` flag and generate output per nmap command, it be cool to throw in a refererence to a tool that aggregates a bunch of nmap xmls into one big one. I have never used these, but thinking about something like one of these: 

https://github.com/CBHue/nMap_Merger/blob/master/nMapMerge.py
https://github.com/opsdisk/scantron/blob/master/console/scan_results/merge_nmap_xml_files.py

Anyway, sorry for the delay in response, busy time of year. Thanks so much for this contribution. I can't want to merge it when it's ready!

**Comment by sethsec-bf** [comment]
Just dropping this note that you could add EFS (and maybe other filesystems like the FSx family to the TODO list as well).

**Comment by wdahlenburg** [comment]
Same here on the delay. Crazy wrap-up to the year! I was glad to finally have some time to tackle this more.

> I like that you split out IPv4 and IPv6. What are your thoughts about separating your loot files to be a privateIP and publicIP loot? So instead of loot/network-ports-ipv4.txt you would have loot/network-ports-private-ipv4.txt and loot/network-ports-public-ipv4.txt ?

IPv4 was split out to public and private in [6e9aa37](https://github.com/BishopFox/cloudfox/pull/19/commits/6e9aa37d4acac0bf4d00655ee51ce28225b10090). I could not find any references that AWS supports private IPv6 or how to differentiate public vs private IPv6 addresses.

> When you do get to it, I think you don't have to have your cloudfox command do this, rather, i think you can ask the user to input the source ip as an optional parameter which will kick off that future functionality that takes source ip into account. i agree that sometimes the user won't know all of the NATing that takes place, but i think we can push that part to the user and just say... given the IP you give us, we will try to give you the output based on that src ip.

Agreed. I think this would be a great add. It may be a stretch, but it'd be neat to cache the data so that it could be queried offline without having to keep retrieving the data, semi-similar to how PMapper stores IAM data and trust relationships.

> You could potentially allow the user to specify their own nmap syntax at the cloudfox command line. On one hand this is probably not that hard to add, but on the other hand, i'm not sure how many would use this. just a thought.

I wanted to give some bare-bones options in the loot file so that users can immediately run those scans and get results. From running some large tests on it, I do think adding the `-Pn` flag as a default would help as ICMP isn't commonly permitted, which can break some of nmap's host discovery.

Personally I've found myself filtering out the lines that don't start with `#` in the loot files and then piping the nmap commands into a bash command where I can tack on any extra flags I like.

```
cat cloudfox-output/aws/<account-folder>/loot/network-ports-private-ipv4.txt | egrep -v "^#" | xargs -I{}  {} -Pn -A
```

The above could be extended out to specify scan output in a designated directory with some unique name.

In contrast, the CSV format does allow for a consistent way to grab and format the data however users would like. This could be used to filter and generate commands with custom nmap flags.

---

> If you do have your nmap commands include the -oA flag and generate output per nmap command, it be cool to throw in a refererence to a tool that aggregates a bunch of nmap xmls into one big one. I have never used these, but thinking about something like one of these:

What are your thoughts on just including that in the wiki documentation?

**Comment by sethsec-bf** [comment]
@wdahlenburg  - I'm getting a panic from generate range in some environments, and i'm pretty sure i tracked it down to when the protocol is ICMP: 

error: 
```
panic: runtime error: makeslice: len out of range

goroutine 2800 [running]:
github.com/BishopFox/cloudfox/aws.generateRange(...)
	/Users/sethart/Documents/projects/cloudfox/aws/network-ports.go:1884
github.com/BishopFox/cloudfox/aws.(*NetworkPortsModule).parseSecurityGroup(0x140023d41c0?, {0x14001d98da0, 0x14001d98d80, 0x14001d98d90, {0x14001385800, 0x2, 0x2}, {0x14001000f80, 0x1, 0x1}, ...})
```

Looking at the debugger, i tracked it down to when  `protocol := aws.ToString(entry.IpProtocol)` is equal to `icmp` and the reason it fails is because it sends `8` as the start and `0` as the end to `generateRange`.  

Here's the offending inbound rule: 

image

The way i see it you could build custom logic to handle `icmp` gracefully, or the logic can just ignore ICMP protocol stuff.

**Comment by sethsec-bf** [comment]
@wdahlenburg - I added an if to just skip the case where the protocol is ICMP for now. I ran it against a large env and i had no other bugs show up.  Let me know if you are good with this, or if you want to handle ICMP. Otherwise, i think this is getting really close to merging into main. Is there more stuff you wanted to add?

**Comment by wdahlenburg** [comment]
@sethsec-bf I generalized the ICMP update you made. The safest approach would be to just allow "-1", "tcp" and "udp" protocols. I don't anticipate any similar weird behavior if a custom protocol is allowed, but the last commit should take a more consistent approach.

image

I added in the `-Pn` flag on the nmap commands as well.

I'm good with the supported services for the PR. Additional services, like FSx, can be added in the future.

**Comment by wdahlenburg** [comment]
@sethsec-bf I took a swing at updating the wiki: https://github.com/wdahlenburg/cloudfox/wiki/AWS-Commands#network-ports. GitHub is apparently finicky about PRs towards wikis, so feel free to use it or modify it as you'd like.

I did see that the Readme update was removed in [1ffd763](https://github.com/BishopFox/cloudfox/pull/19/commits/1ffd763a8581919ee719a169b4a8a3788efcf832). I figure that will get moved back in for the 1.10.0 release right?

**Comment by sethsec-bf** [comment]
@wdahlenburg  - Yea no idea how that got lost, thanks for catching it! 

That wiki update is a thing of beauty and very appreciated. I'll just grab it and drop it in the main wiki now.  Is it OK to use as is, or did you want to anonymize any of that ip/endpoint info?

**Comment by wdahlenburg** [comment]
@sethsec-bf You are welcome to use it as-is. All of the instances were temporary on a test account and have been deleted.

**Pull request merged**
